source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'jekyll', '~> 3.10'
    gem 'bibtex-ruby'
    gem 'jekyll-email-protect'
    gem 'jekyll-github-metadata'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'kramdown-parser-gfm'
    gem 'rouge'
    gem 'webrick'
end
